### ISSUE TITLE
Update shallow equal objects

### ISSUE THREAD

**Issue by ematipico** [moroshko/shallow-equal#1]
I would to request to update the shallow equal for objects with the following one

https://github.com/reactjs/react-redux/blob/master/src/utils/shallowEqual.js

React-redux guys update it recently in order to use the shallowEqual they use in fbjs. This piece of code also manages number cases

**Comment by moroshko** [comment]
Could you describe the issue you are trying to solve, and provide a failing test please?

**Comment by otakustay** [comment]
react-redux's implement actually uses the [Object.is](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) spec, the core difference is `Object.is(0, -0) === false` and `Object.is(NaN, NaN) === true`
