### ISSUE TITLE
Inheritence is not handled well

### ISSUE THREAD

**Issue by Pimm** [moroshko/shallow-equal#3]
The object implementation essentially checks whether:

- `a` and `b` have the same number of _own_ properties, and
- all of the _own_ properties in `a` equal any kind of properties in `b`, including inherited ones.

Because the implementation does not check whether the property in `b` is its own or not, it can be fooled. Try adding this test case:
```javascript
  {
    should: 'return false for the false king',
    objA: {
      crownWearer: true
    },
    objB: (function createFalseKing() {
      var spider = {
        crownWearer: true
      }

      function FalseKing() {
        this.objective = 'world domination';
      }

      FalseKing.prototype = spider;

      return new FalseKing();
    })(),
    result: false
  }

```

**Comment by fivecar** [comment]
A lot of time has passed, but in trying this test case today, it passes. Perhaps [this was added](https://github.com/moroshko/shallow-equal/blob/e10dc36f7ac0f9bee0f034e07ef0bbda8a4495b8/src/objects.ts#L28) a while ago?

Closing this out, now that it (seems to) work.
